ROUTINE-LEVEL ON ERROR UNDO, THROW.

FUNCTION NextCustId RETURNS INTEGER ():
  DEFINE VARIABLE v AS INTEGER NO-UNDO INITIAL 1.
  FOR EACH Customer NO-LOCK BY Customer.CustId DESCENDING:
    v = Customer.CustId + 1.
    LEAVE.
  END.
  RETURN v.
END FUNCTION.

PROCEDURE FindCustomer:
  DEFINE INPUT  PARAMETER pCustId AS INTEGER NO-UNDO.
  DEFINE OUTPUT PARAMETER pFound  AS LOGICAL NO-UNDO.
  FIND Customer NO-LOCK WHERE Customer.CustId = pCustId NO-ERROR.
  pFound = AVAILABLE Customer.
END PROCEDURE.
