{ abl/be/OrderBE.p }
PROCEDURE PostOrder:
  DEFINE INPUT  PARAMETER pReqJson AS LONGCHAR NO-UNDO.
  DEFINE OUTPUT PARAMETER pResJson AS LONGCHAR NO-UNDO.
  RUN CreateOrderFromJson (INPUT pReqJson, OUTPUT pResJson).
END PROCEDURE.
