{ abl/be/ReportsBE.p }

/* REST facade: GET /api/reports/order-summary?from=YYYY-MM-DD&to=YYYY-MM-DD&status=OPEN */
PROCEDURE GetOrderSummary:
  DEFINE INPUT  PARAMETER pFrom   AS CHARACTER NO-UNDO.
  DEFINE INPUT  PARAMETER pTo     AS CHARACTER NO-UNDO.
  DEFINE INPUT  PARAMETER pStatus AS CHARACTER NO-UNDO.
  DEFINE OUTPUT PARAMETER pJson   AS LONGCHAR  NO-UNDO.

  DEFINE VARIABLE dFrom AS DATE NO-UNDO.
  DEFINE VARIABLE dTo   AS DATE NO-UNDO.

  ASSIGN dFrom = ? dTo = ?.
  IF pFrom <> "" THEN dFrom = DATE(INTEGER(SUBSTRING(pFrom,6,2)), INTEGER(SUBSTRING(pFrom,9,2)), INTEGER(SUBSTRING(pFrom,1,4))).
  IF pTo   <> "" THEN dTo   = DATE(INTEGER(SUBSTRING(pTo,6,2)),   INTEGER(SUBSTRING(pTo,9,2)),   INTEGER(SUBSTRING(pTo,1,4))).

  RUN OrderSummaryJson (INPUT dFrom, INPUT dTo, INPUT pStatus, OUTPUT pJson).
END PROCEDURE.
