USING Progress.Json.ObjectModel.*.
{ abl/da/ProductDA.p }
{ abl/util/JsonUtil.p }

PROCEDURE ListProductsJson:
  DEFINE OUTPUT PARAMETER pJson AS LONGCHAR NO-UNDO.
  DEFINE TEMP-TABLE ttProduct NO-UNDO
    FIELD ProdId AS INTEGER FIELD Sku AS CHARACTER FIELD Name AS CHARACTER
    FIELD Price AS DECIMAL FIELD Active AS LOGICAL INDEX pk IS PRIMARY ProdId.
  RUN ListAll OUTPUT TABLE ttProduct.
  RUN WriteTTToJson (TEMP-TABLE ttProduct:DEFAULT-BUFFER-HANDLE, OUTPUT pJson).
END PROCEDURE.
